import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

import Stack_Singly_Linked

s = Stack_Singly_Linked.Singly_Linked_Stack()
s.push(3)
s.push(4)
s.printStack()
print('---------------------')
s.pop()
s.printStack()
print('---------------------')
s.push(1)
s.push(2)
s.push(4)
s.push(5)
s.push(6)
s.push(7)
s.push(8)
s.push(9)
s.printStack()
print('---------------------')
s.pop()
s.pop()
s.pop()
s.pop()
s.pop()
s.pop()
s.pop()
s.pop()
s.pop()
s.pop()
s.pop()